### ISSUE TITLE
Rpc Error

### ISSUE THREAD

**Issue by RedTeamWing** [antonioCoco/RemotePotato0#5]
OS：Windows Server 2012
[*] IStoragetrigger written: 110 bytes
[!] Error. Trigger DCOM failed with status: 0x80040154
![image](https://user-images.githubusercontent.com/25416365/117098806-11ceba00-ada2-11eb-905c-111d06408e4c.png)

**Comment by antonioCoco** [comment]
that rpc error should be "class not registered" and has to do with the CLSID you used.

The clsid you used is the one we hardcoded by default and it has been tested only on windows server 2016 and 2019. If you are using Server 2012 please pick one from this list:

http://ohpe.it/juicy-potato/CLSID/Windows_Server_2012_Datacenter/

for example you can try this: {F87B28F1-DA9A-4F35-8EC0-800EFCF26B83}
