### ISSUE TITLE
http auth error

### ISSUE THREAD

**Issue by knightswd** [antonioCoco/RemotePotato0#8]
OS: windows server 2016
Relaying failed

<img width="948" alt="Screen Shot 2021-08-09 at 17 17 27" src="https://user-images.githubusercontent.com/34396229/128684738-27ea8cbf-ecaf-4ad0-9db5-d8bbbf16757b.png">

RPCSocketListen receive nothing

<img width="1685" alt="Screen Shot 2021-08-09 at 17 22 33" src="https://user-images.githubusercontent.com/34396229/128685187-83ccd782-a18f-4f06-9a2a-877086b154bd.png">

**Comment by antonioCoco** [comment]
The clsid you are using {BA127... does not impersonate the interactive user and as a result you get the auth as anon. Please use one of the clsid in the readme. Next time include also the commandline and output of ntlmrelayx to troubleshoot better the issue .
